const arTranslations = {
    // Auth
    "login": "تسجيل الدخول",
    "register": "تسجيل جديد",
    "email": "البريد الإلكتروني",
    "password": "كلمة المرور",
    "fullName": "الاسم الكامل",
    "signIn": "دخول",
    "signUp": "إنشاء حساب",
    "dontHaveAccount": "ليس لديك حساب؟",
    "alreadyHaveAccount": "لديك حساب بالفعل؟",
    "createOneNow": "أنشئ حساباً الآن",
    "loginHere": "سجل الدخول هنا",
    "signInToContinue": "سجل الدخول للمتابعة",
    "createAccount": "إنشاء حساب",
    "organizationName": "اسم المؤسسة",
    "organizationId": "معرف المؤسسة",
    "createOrganization": "إنشاء مؤسسة",
    "joinOrganization": "الانضمام لمؤسسة",
    "loginFailed": "فشل تسجيل الدخول",
    "registrationFailed": "فشل التسجيل",

    // Sidebar
    "processRepository": "مستودع العمليات",
    "search": "بحث...",
    "aiAssistant": "المساعد الذكي",
    "signOut": "تسجيل الخروج",
    "backToWorkspace": "العودة إلى مساحة العمل",

    // Process Explorer
    "noItemSelected": "لم يتم تحديد عنصر",
    "selectItemPrompt": "اختر مجلداً أو نموذجاً من القائمة الجانبية",
    "folderActions": "إجراءات المجلد",
    "about": "حول",
    "addSubfolder": "إضافة مجلد فرعي",
    "addModel": "إضافة نموذج",
    "noSubfolders": "لا توجد مجلدات فرعية",
    "noModels": "لا توجد نماذج",
    "description": "الوصف",
    "processCode": "كود العملية",
    "steps": "الخطوات",
    "table": "جدول",
    "diagram": "مخطط",
    "overview": "نظرة عامة",
    "subgroups": "مجموعات فرعية",
    "models": "نماذج",
    "editModel": "تعديل النموذج",

    // Editor
    "save": "حفظ",
    "saving": "جاري الحفظ...",
    "generateWithAI": "توليد بالذكاء الاصطناعي",
    "export": "تصدير",
    "properties": "الخصائص",
    "validation": "التحقق",
    "chat": "محادثة",
    "nodeName": "اسم العقدة",
    "nodeType": "نوع العقدة",
    "nodeDescription": "وصف العقدة",
    "deleteNode": "حذف العقدة",
    "zoomIn": "تكبير",
    "zoomOut": "تصغير",
    "fitView": "ملاءمة العرض",
    "pdfDownloadError": "فشل تحميل PDF.",
    "success": "نجاح!",
    "continue": "استمرار",
    "cancel": "إلغاء",
    "delete": "حذف",
    "saveProcess": "حفظ العملية",
    "clearBoard": "مسح اللوحة",
    "clearBoardConfirmTitle": "مسح اللوحة؟",
    "clearBoardConfirmMessage": "هل أنت متأكد أنك تريد مسح اللوحة بالكامل؟ ستفقد جميع التغييرات غير المحفوظة.",
    "deleteProcessConfirmTitle": "حذف العملية؟",
    "deleteProcessConfirmMessage": "هل أنت متأكد أنك تريد حذف هذه العملية؟ لا يمكن التراجع عن هذا الإجراء.",
    "processDeleted": "تم حذف العملية بنجاح!",
    "modelSaved": "تم حفظ النموذج بنجاح!",
    "enterProcessName": "أدخل اسم العملية...",
    "processName": "اسم العملية",
    "loadProcess": "تحميل عملية",
    "noSavedProcesses": "لم يتم العثور على عمليات محفوظة",
    "loading": "جاري التحميل...",
    "newModel": "نموذج جديد",
    "adminDashboard": "لوحة تحكم المسؤول",
    "editProfile": "تعديل الملف الشخصي",
    "exportPDF": "تصدير PDF",
    "grid": "شبكة",
    "snap": "محاذاة",
    "rotateHorizontal": "تدوير أفقي",
    "rotateVertical": "تدوير عمودي",
    "reLayout": "إعادة تخطيط",
    "hideSidebar": "إخفاء الشريط الجانبي",
    "invalidEPCResponse": "تنسيق استجابة Tasree3 غير صالح.",
    "epcUpdated": "تم تحديث مخطط Tasree3 وقواعد البيانات الوصفية.",
    "epcGenerationError": "⚠️ خطأ: تعذر إنشاء Tasree3 أو قواعد البيانات الوصفية.",
    "epcUploadError": "⚠️ خطأ: تعذر معالجة المستند/الصورة وإنشاء المخطط.",
    "settings": "الإعدادات",
    "personalSettings": "الإعدادات الشخصية",
    "organizationSettings": "إعدادات المؤسسة",
    "profile": "الملف الشخصي",
    "profileUpdated": "تم تحديث الملف الشخصي بنجاح",
    "welcomeMessage": "مرحباً في Tasree3 Editor",
    "viewInCanvas": "عرض في Canvas",
    "exportXML": "تصدير XML",
    "xmlExported": "تم تصدير XML بنجاح!",
    "importXML": "استيراد XML",
    "xmlImportError": "فشل استيراد XML. يرجى التحقق من تنسيق الملف.",
    "xmlImported": "تم استيراد XML بنجاح!",
    "share": "مشاركة",
    "copyLink": "نسخ الرابط",
    "shareWhatsApp": "واتساب",
    "shareEmail": "البريد الإلكتروني",
    "linkCopied": "تم نسخ الرابط!",
    "sharePdf": "مشاركة كـ PDF",
    "history": "السجل",
    "insights": "الرؤى",
    "workflowHistory": "سجل سير العمل",
    "trackChanges": "تتبع جميع التغييرات والتحديثات التي تمت على هذا النموذج",
    "user": "المستخدم",
    "action": "الإجراء",
    "dateTime": "التاريخ والوقت",
    "details": "التفاصيل",
    "noActivityHistory": "لا يوجد سجل نشاط",
    "noHistoryPrompt": "لم نتمكن من العثور على أي أحداث تاريخية لهذه العملية.",
    "miningEngine": "محرك التنقيب",
    "generateInsights": "توليد الرؤى",
    "refreshAnalysis": "تحديث التحليل",
    "aiProcessAnalyst": "محلل العمليات بالذكاء الاصطناعي",
    "bottleneck": "عنق الزجاجة",
    "cycleTime": "وقت الدورة",
    "rework": "إعادة العمل",
    "suggestions": "الاقتراحات",
};

export default arTranslations;
