const enTranslations = {
    // Auth
    "login": "Login",
    "register": "Register",
    "email": "Email",
    "password": "Password",
    "fullName": "Full Name",
    "signIn": "Sign In",
    "signUp": "Sign Up",
    "dontHaveAccount": "Don't have an account?",
    "alreadyHaveAccount": "Already have an account?",
    "createOneNow": "Create one now",
    "loginHere": "Login here",
    "signInToContinue": "Sign in to continue",
    "createAccount": "Create Account",
    "organizationName": "Organization Name",
    "organizationId": "Organization ID",
    "createOrganization": "Create Organization",
    "joinOrganization": "Join Organization",
    "loginFailed": "Login failed",
    "registrationFailed": "Registration failed",

    // Sidebar
    "processRepository": "Process Repository",
    "search": "Search...",
    "aiAssistant": "AI Assistant",
    "signOut": "Sign Out",
    "backToWorkspace": "Back to Workspace",

    // Process Explorer
    "noItemSelected": "No item selected",
    "selectItemPrompt": "Select a folder or model from the left panel",
    "folderActions": "Folder Actions",
    "about": "About",
    "addSubfolder": "Add Subfolder",
    "addModel": "Add Model",
    "noSubfolders": "No subfolders",
    "noModels": "No models found",
    "description": "Description",
    "processCode": "Process Code",
    "steps": "Steps",
    "table": "Table",
    "diagram": "Diagram",
    "overview": "Overview",
    "subgroups": "Subgroups",
    "models": "Models",
    "editModel": "Edit Model",

    // Editor
    "save": "Save",
    "saving": "Saving...",
    "generateWithAI": "Generate with AI",
    "export": "Export",
    "properties": "Properties",
    "validation": "Validation",
    "chat": "Chat",
    "nodeName": "Node Name",
    "nodeType": "Node Type",
    "nodeDescription": "Node Description",
    "deleteNode": "Delete Node",
    "zoomIn": "Zoom In",
    "zoomOut": "Zoom Out",
    "fitView": "Fit View",
    "pdfDownloadError": "Failed to download PDF.",
    "success": "Success!",
    "continue": "Continue",
    "cancel": "Cancel",
    "delete": "Delete",
    "saveProcess": "Save Process",
    "clearBoard": "Clear Board",
    "clearBoardConfirmTitle": "Clear Board?",
    "clearBoardConfirmMessage": "Are you sure you want to clear the entire board? All unsaved changes will be lost.",
    "deleteProcessConfirmTitle": "Delete Process?",
    "deleteProcessConfirmMessage": "Are you sure you want to delete this process? This action cannot be undone.",
    "processDeleted": "Process deleted successfully!",
    "modelSaved": "Model saved successfully!",
    "enterProcessName": "Enter process name...",
    "processName": "Process Name",
    "loadProcess": "Load Process",
    "noSavedProcesses": "No saved processes found",
    "loading": "Loading...",
    "newModel": "New Model",
    "adminDashboard": "Admin Dashboard",
    "editProfile": "Edit Profile",
    "exportPDF": "Export PDF",
    "grid": "Grid",
    "snap": "Snap",
    "rotateHorizontal": "Rotate Horizontal",
    "rotateVertical": "Rotate Vertical",
    "reLayout": "Re-Layout",
    "hideSidebar": "Hide Sidebar",
    "invalidEPCResponse": "Invalid Tasree3 response format.",
    "epcUpdated": "The Tasree3 diagram and metadata rules have been updated.",
    "epcGenerationError": "⚠️ Error: Could not generate Tasree3 or metadata rules.",
    "epcUploadError": "⚠️ Error: Could not process the document/image and generate diagram.",
    "settings": "Settings",
    "personalSettings": "Personal Settings",
    "organizationSettings": "Organization Settings",
    "profile": "Profile",
    "profileUpdated": "Profile updated successfully",
    "welcomeMessage": "Welcome to Tasree3 Editor",
    "viewInCanvas": "View in Canvas",
    "exportXML": "Export XML",
    "xmlExported": "XML exported successfully!",
    "importXML": "Import XML",
    "xmlImportError": "Failed to import XML. Please check the file format.",
    "xmlImported": "XML imported successfully!",
    "share": "Share",
    "copyLink": "Copy Link",
    "shareWhatsApp": "WhatsApp",
    "shareEmail": "Email",
    "linkCopied": "Link Copied!",
    "sharePdf": "Share as PDF",
    "history": "History",
    "insights": "Insights",
    "workflowHistory": "Workflow History",
    "trackChanges": "Track all changes and updates aimed at this model",
    "user": "User",
    "action": "Action",
    "dateTime": "Date & Time",
    "details": "Details",
    "noActivityHistory": "No Activity History",
    "noHistoryPrompt": "We couldn't find any historical events for this process.",
    "miningEngine": "Mining Engine",
    "generateInsights": "Generate Insights",
    "refreshAnalysis": "Refresh Analysis",
    "aiProcessAnalyst": "AI Process Analyst",
    "bottleneck": "Bottleneck",
    "cycleTime": "Cycle Time",
    "rework": "Rework",
    "suggestions": "Suggestions",
};

export default enTranslations;
